### PR TITLE
Run through a formatter

### PR DESCRIPTION
**Pull request by mbax**
This might not be the formatting you want, 100%. If there's something not quite right let me know.  I figured a bit of enforced consistency would be healthy.

Current Eclipse formatter: http://pastie.org/private/k6nu9y4f4pxi99bybnqtg

### CODE REVIEW

**Comment by tonybruess** [comment]
I wonder if H31IX would be ok with not putting curly brackets on new lines...

**Comment by mbax** [comment]
Sadly don't have the IRC log thanks to my VPS asploding, but he'd said that he rather likes doing it that way today when we were chatting about it.  Lets you really see the separation of stuff.

**Comment by SuperSpyTX** [comment]
I'm also getting "This pull request cannot be automatically merged." when trying to merge this.

Also we'll have to wait for mighty @h31ix

**Comment by mbax** [comment]
(Submitting an updated version of this in the futures)

**Pull request closed without merging**
