### PR TITLE
Fixes false positives with modified playerWalkSpeed

### PR DESCRIPTION
**Pull request by ELCHILEN0**
Fixes bugs with player.setWalkSpeed() by adding the difference of the new speed to the maximum allowed speed.

### CODE REVIEW

**Comment by gravitylow** [comment]
Where does the magic number (0.2) come from?

**Comment by ELCHILEN0** [comment]
The 0.2 is the default player walkSpeed.  Since the change is added to the max level and the max level takes into account the walkSpeed I thought it best to only apply the difference and so as to maintain accuracy and not allow a minor potential bypass.

**Comment by gravitylow** [comment]
And you've tested to make sure this change works as intended?

**Comment by ELCHILEN0** [comment]
The tests that I performed are outlined below.

Before maximum speed modification:
- Occasional hack level raises for a .1 increase to the player speed.
- Kicks due to flight/speed using Nodus at a speed of 1.

After maximum speed modification:
- No hack level warnings for a .1 increase to the player speed.
- Kicks due to flight/speed using Nodus at a speed of 1.

The change works as intended.  I tested with default walking, sprinting and jump sprinting.  The only error I could potentially see is a player falling from extreme altitudes and overcoming the air resistance built into Minecraft.  There they could potentially go past the maximum speed however this would be a potential bug with or without the change.

**Comment by gravitylow** [comment]
Excellent. I'll have it up on a dev build and get people to test.

Thanks, pulled.

**Pull request closed without merging**
